# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(100, 100, 100, 100)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_all = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_all.sizePolicy().hasHeightForWidth())
        self.btn_all.setSizePolicy(sizePolicy)
        self.btn_all.setStyleSheet("")
        self.btn_all.setObjectName("btn_all")
        self.gridLayout.addWidget(self.btn_all, 0, 0, 1, 1)
        self.btn_single = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_single.sizePolicy().hasHeightForWidth())
        self.btn_single.setSizePolicy(sizePolicy)
        self.btn_single.setObjectName("btn_single")
        self.gridLayout.addWidget(self.btn_single, 0, 1, 1, 1)
        self.btn_lh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_lh.sizePolicy().hasHeightForWidth())
        self.btn_lh.setSizePolicy(sizePolicy)
        self.btn_lh.setObjectName("btn_lh")
        self.gridLayout.addWidget(self.btn_lh, 1, 0, 1, 1)
        self.btn_h = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_h.sizePolicy().hasHeightForWidth())
        self.btn_h.setSizePolicy(sizePolicy)
        self.btn_h.setObjectName("btn_h")
        self.gridLayout.addWidget(self.btn_h, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # 获取屏幕中心位置
        desktop = QtWidgets.QApplication.desktop()
        screen_width = desktop.width()
        screen_height = desktop.height()
        window_width = MainWindow.width()
        window_height = MainWindow.height()
        MainWindow.move(
            (screen_width - window_width) // 2,
            (screen_height - window_height) // 2
        )

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_all.setText(_translate("MainWindow", "All Situation"))
        self.btn_single.setText(_translate("MainWindow", "Single Stock\n"
" Situation"))
        self.btn_lh.setText(_translate("MainWindow", "Login History"))
        self.btn_h.setText(_translate("MainWindow", "History"))
